const GET_TODOS = "GET_TODOS";

const REGISTER_USER = " REGISTER_USER";

const REGISTER_ERROR = "REGISTER_ERROR";

const REGISTER_SUCCESS = "REGISTER_SUCCESS";

const LOGIN_SUCCESS = "LOGIN_SUCCESS";

const LOGIN_ERROR = "LOGIN_ERROR";

const SIGNOUT_ERROR = "SIGNOUT_ERROR";

const SIGNOUT_USER = " SIGNOUT_USER";

const ADD_TODO_REQUEST = "ADD_TODO_REQUEST";

const ADD_TODO_ERROR = "ADD_TODO_ERROR";

const GET_TODO_ERROR = "GET_TODO_ERROR";

const GET_TODO = "GET_TODO";

const DELETE_TODO = "DETELE_TODO";

const DELETE_ERROR = "DELETE_ERROR";

const UPDATE_TODO = "UPDATE_TODO";

const UPDATE_ERROR = "UPDATE_ERROR";

export {
  GET_TODOS,
  REGISTER_ERROR,
  REGISTER_USER,
  REGISTER_SUCCESS,
  LOGIN_SUCCESS,
  LOGIN_ERROR,
  SIGNOUT_ERROR,
  SIGNOUT_USER,
  ADD_TODO_REQUEST,
  ADD_TODO_ERROR,
  GET_TODO_ERROR,
  GET_TODO,
  DELETE_TODO,
  DELETE_ERROR,
  UPDATE_TODO,
  UPDATE_ERROR,
};
