const GET_TODOS = "GET_TODOS";

const REGISTER_USER = " REGISTER_USER";

const REGISTER_ERROR = "REGISTER_ERROR";

const REGISTER_SUCCESS = "REGISTER_SUCCESS";

const LOGIN_SUCCESS = "LOGIN_SUCCESS";

const LOGIN_ERROR = "LOGIN_ERROR";

const SIGNOUT_ERROR = "SIGNOUT_ERROR";

const SIGNOUT_USER = " SIGNOUT_USER";

export {
  GET_TODOS,
  REGISTER_ERROR,
  REGISTER_USER,
  REGISTER_SUCCESS,
  LOGIN_SUCCESS,
  LOGIN_ERROR,
  SIGNOUT_ERROR,
  SIGNOUT_USER,
};
